version: 2.1

workflows:
  challenge-app:
    jobs:
      - build-and-test
      - assemble:
          requires:
            - build-and-test

aliases:
  build-default-settings:
    &build-default-settings
    working_directory: ~/code
    docker:
      - image: cimg/android:2022.06
    environment:
      JVM_OPTS: -Xmx2G
      GRADLE_OPTS: -Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2
        -Dorg.gradle.jvmargs="-Xmx2G -XX:MaxPermSize=1G
        -XX:+HeapDumpOnOutOfMemoryError"
        -Dkotlin.compiler.execution.strategy=in-process
        -Dkotlin.incremental=false

jobs:
  build-and-test:
    <<: *build-default-settings
    steps:
      - checkout
      - run:
          name: Assemble
          command: ./gradlew app:build --stacktrace
      - run:
          name: Run Tests
          command: ./gradlew app:test --stacktrace
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results/junit
      - store_artifacts:
          path: app/build/reports
          destination: reports
    resource_class: medium

  assemble:
    <<: *build-default-settings
    steps:
      - checkout
      - run:
          name: Assemble builds
          command: ./gradlew app:assemble --stacktrace
      - store_artifacts:
          path: app/build/outputs/apk/
    resource_class: medium
